inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Style/Documentation:
  Enabled: false
