inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 40

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/StubbedMock:
  Enabled: False

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false
