name: Build-test

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build-test:
    strategy:
      matrix:
        ruby-version: [2.7.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0, head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Test
      run: make -f Makefile.docker test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        parallel: true
        flag-name: ${{ matrix.ruby-version }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint
      run: make -f Makefile.docker lint
  finish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
